# Generated by Django 4.1.3 on 2022-12-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cohort_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='origin',
            field=models.BooleanField(default=False),
        ),
    ]
