# Generated by Django 4.1.3 on 2022-12-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_cohort_email_alter_subcohort_cohort_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortpdfs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
