# Generated by Django 4.1.3 on 2022-12-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_cohortpdfs_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohortpdfs',
            name='content',
        ),
    ]
