# Generated by Django 4.1.3 on 2022-12-06 20:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_cohortpdfs_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortpdfs',
            name='content_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 12, 6, 20, 55, 17, 735935, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohortpdfs',
            name='content_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
