# Generated by Django 4.1.3 on 2022-12-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cohortpdfs_content_date_cohortpdfs_content_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohortstudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='base.cohort')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userdata')),
            ],
        ),
    ]
