# Generated by Django 4.1.4 on 2022-12-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_cohortstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='facedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=200)),
            ],
        ),
    ]
