# Generated by Django 4.1.4 on 2022-12-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_question_mcq_cq'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.IntegerField(default=0),
        ),
    ]
