# Generated by Django 4.1.4 on 2022-12-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_question_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='readattempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('pdf', models.IntegerField()),
                ('total', models.IntegerField()),
                ('onscreen', models.IntegerField()),
                ('sus', models.IntegerField()),
            ],
        ),
    ]
