# Generated by Django 4.1.4 on 2022-12-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_readattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortpdfs',
            name='qn_published',
            field=models.BooleanField(default=False),
        ),
    ]
