# Generated by Django 4.1.4 on 2022-12-24 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_cohortpdfs_qn_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizattempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(default=0)),
                ('starttime', models.TimeField(auto_now_add=True)),
                ('email', models.ForeignKey(db_constraint=False, default='0', on_delete=django.db.models.deletion.CASCADE, to='base.userdata')),
            ],
        ),
    ]
