# Generated by Django 4.1.4 on 2022-12-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_quizattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentans', models.CharField(max_length=600)),
                ('email', models.ForeignKey(db_constraint=False, default='0', on_delete=django.db.models.deletion.CASCADE, to='base.userdata')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question')),
            ],
        ),
    ]
