# Generated by Django 4.1.4 on 2022-12-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_quizattempt_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='source',
            field=models.IntegerField(default=0),
        ),
    ]
